spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/i2twm/config-repo.git
          username: i2twmx@gmail.com
          password: Aa131416
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"