spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/i2twmx/config-repo
          username: i2twmx@gmail.com
          password: Aa131416
          basedir: C:\ideawork\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888